In [72]:
# https://nasa-openscapes.github.io/2021-Cloud-Hackathon/tutorials/02_Data_Discovery_CMR-STAC_API.html

from pystac_client import Client  
from collections import defaultdict    
import json
import geopandas
# import geoviews as gv
from cartopy import crs
# gv.extension('bokeh', 'matplotlib')
import geopandas as gpd

In [73]:
# find hls tiles given a point

def find_hls_tiles(point=False, band=False, limit=False, collections = ['HLSL30.v2.0', 'HLSS30.v2.0'], date_range = False):

    STAC_URL = 'https://cmr.earthdata.nasa.gov/stac'


    catalog = Client.open(f'{STAC_URL}/LPCLOUD/')



    try:
        x, y = point[0], point[1]
        # print(x,y)
    except TypeError:
        print("Point must be in the form of [lon,lat]")
        raise

    point = geopandas.points_from_xy([x],[y])
    point = point[0]



    # JOHN - THIS IS WHERE YOU WOULD ADD IN SEARCH PARAMETERS
    if date_range:

        search = catalog.search(
            collections=collections, intersects = point, datetime=date_range)
    else:
        search = catalog.search(
            collections=collections, intersects = point)



    # print(f'{search.matched()} Tiles Found...')


    item_collection = search.get_all_items()

    if limit:
        item_collection = item_collection[:limit]

    if band:
        links = []
        if type(band) == list:
            for i in item_collection:
                for b in band:
                    link = i.assets[b].href
                    # print(link)
                    links.append(link)
        
        else:
            for i in item_collection:
                link = i.assets[band].href
                links.append(link)
    
    else:
        links =[]
        for i in item_collection:
            # print(i.assets)
            for key in i.assets:
                if key.startswith('B'):
                    # link = i.assets[key].href.replace('https://data.lpdaac.earthdatacloud.nasa.gov/', 's3://')
                    link = i.assets[key].href

                    # print(link)
                    links.append(link)

    return links

In [74]:
# given a reach ID, find the nodes

import glob
import netCDF4
import os
import numpy as np


data_dir = '/home/confluence/data/mnt/input/sword'





def get_reach_nodes(data_dir, reach_id):

    all_nodes = []

    files = glob.glob(os.path.join(data_dir, '*'))
    print(f'Searching across {len(files)} continents for nodes...')

    for i in files:

        rootgrp = netCDF4.Dataset(i, "r", format="NETCDF4")

        node_ids_indexes = np.where(rootgrp.groups['nodes'].variables['reach_id'][:].data.astype('U') == str(reach_id))

        if len(node_ids_indexes[0])!=0:
            for y in node_ids_indexes[0]:
                node_id = str(rootgrp.groups['nodes'].variables['node_id'][y].data.astype('U'))
                all_nodes.append(node_id)



            # all_nodes.extend(node_ids[0].tolist())

        rootgrp.close()

    print(f'Found {len(set(all_nodes))} nodes...')
    return list(set(all_nodes))





# get_reach_nodes(data_dir,74270100221)

In [75]:
# given a reach ID, find the lat/lon points of all nodes



import glob
import netCDF4
import os
import numpy as np

data_dir = '/home/confluence/data/mnt/input/sword'


def get_reach_node_cords(data_dir, reach_id):

    all_nodes = []

    files = glob.glob(os.path.join(data_dir, '*'))
    print(f'Searching across {len(files)} continents for nodes...')

    for i in files:

        rootgrp = netCDF4.Dataset(i, "r", format="NETCDF4")

        node_ids_indexes = np.where(rootgrp.groups['nodes'].variables['reach_id'][:].data.astype('U') == str(reach_id))

        if len(node_ids_indexes[0])!=0:
            for y in node_ids_indexes[0]:

                lat = str(rootgrp.groups['nodes'].variables['x'][y].data.astype('U'))
                lon = str(rootgrp.groups['nodes'].variables['y'][y].data.astype('U'))
                all_nodes.append([lat,lon])



            # all_nodes.extend(node_ids[0].tolist())

        rootgrp.close()

    print(f'Found {len(all_nodes)} nodes...')
    return all_nodes











In [76]:
# given a reach ID, create download links for any hls tiles that intersect the nodes in the reach


def find_download_links_for_reach_tiles(data_dir, reach_id):
    node_coords = get_reach_node_cords(data_dir,reach_id)
    all_links = []
    for i in node_coords:
        print(i)
        links = find_hls_tiles(i,limit=1)
        print(links)
        all_links.extend(links)

    return list(set(all_links))

In [77]:
#generate

import pandas as pd


df = pd.read_csv('/data/data/downloads/Aqusat_TSS_v1.csv')

In [78]:
dates = df['date'];dates

0        2001-06-04
1        1992-06-02
2        2002-06-05
3        1992-08-19
4        1984-09-18
            ...    
32141    2008-08-11
32142    2017-10-16
32143    2013-09-27
32144    2016-07-18
32145    2010-10-13
Name: date, Length: 32146, dtype: object

In [79]:
date_range = "2001-06-04T00:00:00Z"

In [80]:
lat, lon, date = str(df.iloc[100]['lat']), str(df.iloc[100]['long']), df.iloc[0]['date']
i = [lat,lon]
# i = ['-89.4447009885916', '37.4435521655434']
# print(lat,lon,date)

In [81]:
from ipywidgets import IntProgress
from IPython.display import display
import time
import pandas as pd

# max_count = 100


# https://rafatieppo.github.io/post/2018_12_01_juliandate/
import datetime

def datestdtojd (stddate):
    fmt='%Y-%m-%d'
    sdtdate = datetime.datetime.strptime(stddate, fmt)
    sdtdate = sdtdate.timetuple()
    jdate = sdtdate.tm_yday
    return(stddate[:4]+str(jdate))

def jdtodatestd (jdate):
    fmt = '%Y%j'
    datestd = datetime.datetime.strptime(jdate, fmt).date()
    out = datestd.strftime( '%Y-%m-%d')
    return out


import pandas as pd


df = pd.read_csv('/data/data/downloads/Aqusat_TSS_v1.csv')


def ssc_json_gen(aquasat_path):
    ssc_dict = {}

    # read in aquasat
    df = pd.read_csv(aquasat_path)

    f = IntProgress(min=0, max=len(df)) # instantiate the bar
    display(f) # display the bar

    fails = 0

    for i in range(len(df)):
        lat, lon, date = str(df.iloc[i]['lat']), str(df.iloc[i]['long']), df.iloc[0]['date']
        try:
            # date = datestdtojd('2013-01-13')
            # print(date)
            links = find_hls_tiles(point=[lon, lat])
            if len(links)>0:
                date_list = []
                for l in links:
                    date = l.split('/')[-1].split('.')[3][:7]
                    date_list.append(date)

                date_list = [jdtodatestd(x) for x in set(date_list)]

                date_list.sort(key=lambda date: datetime.datetime.strptime(date, '%Y-%m-%d'))


                

                date_dict = {}
                for z in date_list:
                    
                    link_list_for_date = []
                    for y in links:
                        date = y.split('/')[-1].split('.')[3][:7]
                        date = jdtodatestd(date)
                        if date == z:
                            link_list_for_date.append(y)
                    
                    # build_entry
                    
                    date_dict[z] = link_list_for_date

                ssc_dict[str(lon) +','+ str(lat)]  = date_dict
                # break
                
        except:
            fails +=1
        f.value += 1 # signal to increment the progress bar
        time.sleep(.1)
    print(f'Total fails: {fails} ')
    print(f'Total Success: {len(df)-fails}')
    return ssc_dict

    


In [82]:
aqua_path = '/data/data/downloads/Aqusat_TSS_v1.csv'

jj = ssc_json_gen(aqua_path)

IntProgress(value=0, max=32146)

In [ ]:
jj['-92.141332,47.529724']['2022-11-12']

['https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T15TWN.2022316T165848.v2.0/HLS.L30.T15TWN.2022316T165848.v2.0.B05.tif',
 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T15TWN.2022316T165848.v2.0/HLS.L30.T15TWN.2022316T165848.v2.0.B09.tif',
 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T15TWN.2022316T165848.v2.0/HLS.L30.T15TWN.2022316T165848.v2.0.B07.tif',
 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T15TWN.2022316T165848.v2.0/HLS.L30.T15TWN.2022316T165848.v2.0.B01.tif',
 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T15TWN.2022316T165848.v2.0/HLS.L30.T15TWN.2022316T165848.v2.0.B03.tif',
 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30.020/HLS.L30.T15TWN.2022316T165848.v2.0/HLS.L30.T15TWN.2022316T165848.v2.0.B06.tif',
 'https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/HLSL30

In [ ]:
# Serializing json
json_object = json.dumps(jj, indent=4)
 
# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)

In [ ]:
# import pandas as pd


# df = pd.read_csv('/data/data/downloads/Aqusat_TSS_v1.csv')

# for i in range(len(df)):
#     # print(i)
#     lat, lon, date = str(df.iloc[i]['lat']), str(df.iloc[i]['long']), df.iloc[0]['date']
#     try:
#         #date not working
#         date = "2013-13-01T00:00:00Z/2014-13-01T00:00:00Z" 
#         links = find_hls_tiles(point=[lon, lat])
#         if len(links)>0:
#             print(links)
#             break
#     except:
#         pass

In [ ]:
# for i in range(10):
#     print(i)

In [ ]:
# https://nasa-openscapes.github.io/2021-Cloud-Hackathon/tutorials/05_Data_Access_Direct_S3.html

# need to make netrc file



# %matplotlib inline
# import matplotlib.pyplot as plt
from datetime import datetime
import os
import requests
import boto3
import numpy as np
import xarray as xr
import rasterio as rio
from rasterio.session import AWSSession
from rasterio.plot import show
import rioxarray
# import geoviews as gv
# import hvplot.xarray
# import holoviews as hv
# gv.extension('bokeh', 'matplotlib')


s3_cred_endpoint = 'https://data.lpdaac.earthdatacloud.nasa.gov/s3credentials'

def get_temp_creds():
    temp_creds_url = s3_cred_endpoint
    return requests.get(temp_creds_url).json()


temp_creds_req = get_temp_creds()


session = boto3.Session(aws_access_key_id=temp_creds_req['accessKeyId'], 
                        aws_secret_access_key=temp_creds_req['secretAccessKey'],
                        aws_session_token=temp_creds_req['sessionToken'],
                        region_name='us-west-2')


rio_env = rio.Env(AWSSession(session),
                  GDAL_DISABLE_READDIR_ON_OPEN='EMPTY_DIR',
                  GDAL_HTTP_COOKIEFILE=os.path.expanduser('~/cookies.txt'),
                  GDAL_HTTP_COOKIEJAR=os.path.expanduser('~/cookies.txt'))

            
rio_env.__enter__()

hls_da = rioxarray.open_rasterio(jj["-92.141332,47.529724"]["2013-05-11"][0], chuncks=True)

test = hls_da.values

print(test)

[[[1120 1104 1126 ... 2014 2082 2171]
  [ 998  859  890 ... 1966 2051 2188]
  [ 953  743  782 ... 2031 2088 2172]
  ...
  [3467 3394 3233 ... 3795 3576 3397]
  [3542 3445 3266 ... 3767 3374 3346]
  [3533 3497 3365 ... 3772 3607 3699]]]
